### PR TITLE
Fix Bug #121

### PR DESCRIPTION
**Pull request by johnmarinelli**
I'm not sure if you meant to set dispose={null} for any particular reason, but I just removed it.  not sure if this has further implications, if it does, let me know

### CODE REVIEW

**Comment by gsimone** [comment]
Tagging paul for this @drcmda, I'm still not too confident about the state of dispose

**Comment by lojjic** [comment]
The fact that troika is making the material's `dispose` method non-writable is an oversight, and I can fix that. I think that would clear this up, though it's still worth having Paul weigh in on whether it's desirable here.

**Comment by lojjic** [comment]
troika-three-text v0.32.0 should fix the error when trying to overwrite the dispose method.

**Comment by johnmarinelli** [comment]
@lojjic yep looks like it.  i will close this PR then.  Thanks!

**Pull request closed without merging**
