### PR TITLE
add map controls

### PR DESCRIPTION
**Pull request by piducancore**
The title says it all, I added MapControls:

```js
// import
import { MapControls } from "drei"

// and use
<MapControls />
```

### CODE REVIEW

**Comment by drcmda** [comment]
nice, thanks!

**Comment by neftaly** [comment]
Is this the same as OrbitControls? I missing something here?

**Comment by drcmda** [comment]
yes, it's a variant of it. threejs/jsm/.../OrbitControls has two exports, OrbitControls and MapControls

**Comment by neftaly** [comment]
Ah, I didn't notice the different import :) Thanks!

**Pull request merged**
