### PR TITLE
Added line component

### PR DESCRIPTION
**Pull request by giulioz**

### CODE REVIEW

**Comment by gsimone** [comment]
You should add the codesandbox badge to the entry in the index (line 40)

**Comment by giulioz** [comment]
You are right, done

**Comment by drcmda** [comment]
i think this could still use some small makeover

```jsx
  return (
    <line2>
      <lineGeometry attach="geometry" />
      <lineMaterial attach="material" {...rest} />
    </line2>
  )
```

heres an example of declarative line2: https://codesandbox.io/s/react-three-fiber-line2-wireframe-iup24

typescript needs something like this

```jsx
import { extend, useThree, ReactThreeFiber } from 'react-three-fiber'
import { LineGeometry } from 'three/examples/jsm/lines/LineGeometry'
import { LineMaterial, LineMaterialParameters } from 'three/examples/jsm/lines/LineMaterial'
import { Line2 } from 'three/examples/jsm/lines/Line2'

extend({ Line2, LineGeometry, LineMaterial })

declare global {
  namespace JSX {
    // eslint-disable-next-line @typescript-eslint/interface-name-prefix
    interface IntrinsicElements {
      line2: ReactThreeFiber.Object3DNode<Line2, typeof Line2>
      lineGeometry: ReactThreeFiber.Object3DNode<LineGeometry, typeof LineGeometry>
      lineMaterial: ReactThreeFiber.Object3DNode<LineMaterial, typeof LineMaterial>
    }
  }
}
```

@giulioz would you attempt it?

**Comment by giulioz** [comment]
Yes of course, i'll do it tomorrow.

**Pull request merged**
