### PR TITLE
Adds useHelper hook

### PR DESCRIPTION
**Pull request by gsimone**

### CODE REVIEW

**Comment by drcmda** [comment]
is it possible to express args as useHelper(ref, type, arg1, arg2, arg3, ...) ? or was that the reason why you couldnt figure the ts types out initially?

**Comment by gsimone** [comment]
I could probably do it by abusing any, I also think that's a better API

**Comment by drcmda** [comment]
sure, let's do that and someone will fix it later

**Comment by gsimone** [comment]
Done ✅

**Comment by drcmda** [comment]
nice, thanks, btw, i saw your recent edits and prs, would you like to help maintain with shared author rights?

**Comment by gsimone** [comment]
Sure, I'd be glad to help

**Pull request merged**
