### PR TITLE
Add Reflector component

### PR DESCRIPTION
**Pull request by flo-pereira**
Adds Reflector component.

I recreated the threejs exemple to illustrate:

> https://codesandbox.io/s/jolly-benz-pmk9j

> Original: https://threejs.org/examples/#webgl_mirror

### CODE REVIEW

**Comment by gsimone** [comment]
Hey, looking great, can you add a story to the storybook and an entry in the readme? The storybook will be previewable here https://deploy-preview-73--drei-storybook.netlify.app/

**Comment by flo-pereira** [comment]
done 👍

**Comment by drcmda** [comment]
this is a nice idea! the only thing i dont understand is the cloneElement just to add attach. the problem with cloning is that it breaks composition:

```jsx
function Foo = () => <planeBufferGeometry args={[2, 5]} />

<Reflector>
  <Foo />
</Reflector>
```

I think if we explain that attach is needed it would be more versatile.

btw attach will fall be automated in v5 anyway, you don't have to write out for materials and geometries.

**Comment by flo-pereira** [comment]
You're right @drcmda, it's fixed ! 👍

**Pull request merged**
